Project3/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders' #Need for namespacing in reverse()
urlpatterns = [
    path("", views.home, name="home")
]

Project3/pizza/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('users.urls')),
    path("home/", include("orders.urls")),
    path("admin/", admin.site.urls),
]

Project3/users/urls.py
from django.urls import path

from . import views

app_name = 'users' #for namespacing in reverse()
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register')
]

Project3/orders/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
# Inherting models.model just establishes this class as a Django model.
class Pasta(models.Model):
    name = models.CharField(max_length=64)
    value = models.FloatField()

    def __str__(self):
        return f"{self.name} {self.value}"

class Salad(models.Model):
    name = models.CharField(max_length=64)
    value = models.FloatField()

    def __str__(self):
        return f"{self.name} {self.value}"

class Dinner_platter(models.Model):
    type = models.CharField(max_length=64)
    small_value = models.FloatField()
    large_value = models.FloatField()

    def __str__(self):
        return f"{self.type} {self.small_value} {self.large_value}"

class Regular(models.Model):
    type = models.CharField(max_length=64)
    small_value = models.FloatField()
    large_value = models.FloatField()

    def __str__(self):
        return f"{self.type} {self.small_value} {self.large_value}"

class Sicilian(models.Model):
    type = models.CharField(max_length=64)
    small_value = models.FloatField()
    large_value = models.FloatField()

    def __str__(self):
        return f"{self.type} {self.small_value} {self.large_value}"

class Topping(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"

class Sub(models.Model):
    type = models.CharField(max_length=64)
    small_value = models.FloatField()
    large_value = models.FloatField()

    def __str__(self):
        return f"{self.type} {self.small_value} {self.large_value}"

class Addon(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"

Project3/users/models.py
from django.db import models

# Create your models here.

Project3/orders/views.py
from django.http import HttpResponse
from django.shortcuts import render

from .models import Regular, Sicilian, Topping, Sub, Addon, Dinner_platter, Salad, Pasta
# Create your views here.
def home(request):
    context = {
        "regulars": Regular.objects.all(),
        "sicilians": Sicilian.objects.all(),
        "pastas": Pasta.objects.all(),
        "salads": Salad.objects.all(),
        "dinner_platters": Dinner_platter.objects.all(),
        "subs": Sub.objects.all(),
        "addons": Addon.objects.all(),
        "toppings": Topping.objects.all(),
    }

    return render(request, 'orders/home.html', context)

Project3/users/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.db import IntegrityError

# Create your views here.

def index(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html', {'message': None})

    return HttpResponseRedirect(reverse('orders:home'))

def login_view(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse("users:index"))
    else:
        return render(request, "users/login.html", {"message": "Invalid credentials."})

def logout_view(request):
    logout(request)
    return render(request, "users/login.html", {"message": "Logged out."})

def register_view(request):
    if request.method == 'GET':
        return render(request, 'users/register.html', {'message': None})
    else:
        username_register = request.POST.get('username_register')
        password_register = request.POST.get('password_register')
        email_register = request.POST.get('email_register')
        try:
            user = User.objects.create_user(username_register, email_register, password_register)
            return HttpResponseRedirect(reverse("users:index"))
        #IntegrityError exception occurs where there is also a user with that username
        except IntegrityError as e:
            return render(request, 'users/register.html', {'message': e.__cause__ })

Project3/orders/templates/orders/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

Project3/orders/templates/orders/home.html
{% extends "orders/base.html" %}

{% block head %}
    <title>Pinocchio</title>
    {% load static %}
    <link rel="stylesheet" href="/static/orders/css/style.css">
    <script src="/static/orders/js/home.js"></script>
{% endblock %}

{% block body %}
    <a href="{% url 'users:logout' %}">Logout</a>
    <h1>{{ request.user }}</h1>
    <form id='food_selection_form'>
        {% csrf_token %}
        <select id="food_type">
            <option value=regular>Regular Pizza</option>
            <option value=sicilian>Sicilian Pizza</option>
            <option value=pasta>Pasta</option>
            <option value=salad>Salad</option>
            <option value=dinner_platter>Dinner_platter</option>
        </select>
    </form>

    <form id="regular" style='display: none;'>
        {% csrf_token %}
        <h2>Regular Pizzas</h2>
        <select id="regular_type">
            {% for regular in regulars %}
                <option value="{{ regular.id }}">{{ regular }}</option>
            {% endfor %}
        </select>
    </form>

    <form id="sicilian" style='display: none;'>
        {% csrf_token %}
        <h2>Sicilian Pizzas</h2>
        <select id="sicilian_type">
            {% for sicilian in sicilians %}
                <option value="{{ sicilian.id }}">{{ sicilian }}</option>
            {% endfor %}
        </select>
    </form>

    <form id="pasta" style='display: none;'>
        {% csrf_token %}
        <h2>Pastas</h2>
        <select id="pasta_type">
            {% for pasta in pastas %}
                <option value="{{ pasta.id }}">{{ pasta }}</option>
            {% endfor %}
        </select>
    </form>

    <form id="salad" style='display: none;'>
        {% csrf_token %}
        <h2>Salads</h2>
        <select id="salad_type">
            {% for salad in salads %}
                <option value="{{ salad.id }}">{{ salad }}</option>
            {% endfor %}
        </select>
    </form>

    <form id="dinner_platter" style='display: none;'>
        {% csrf_token %}
        <h2>Dinner_platters</h2>
        <select id="dinner_platter_type">
            {% for dinner_platter in dinner_platters %}
                <option value="{{ dinner_platter.id }}">{{ dinner_platter }}</option>
            {% endfor %}
        </select>
    </form>

    <form id="topping_form">
        {% csrf_token %}
        <h2>Toppings</h2>
        {% for topping in toppings %}
            <input type="checkbox" class="check_class" name="toppings" value="{{topping.name}}">{{topping.name}}<br>
        {% endfor %}
    </form>

    <form id="size_form">
        {% csrf_token %}
        <h2>choose the size</h2>
        <input type="radio" name="size" id="small" value="small">Small<br>
        <input type="radio" name="size" id="large" value="large">Large<br>
    </form>

    <input id="submit_to_basket" type="submit" value="Submit to basket">
{% endblock %}

Project3/users/templates/users/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Users</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

Project3/users/templates/users/login.html
{% extends "users/base.html" %}

{% block body %}
<h1>Login</h1>
{% if message %}
    <div>
        {{ message }}
    </div>
{% endif %}
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input name="username" type="text" placeholder="username"/>
    <input name="password" type="password" placeholder="password"/>
    <input type="submit" value="Login"/>
</form>

<h2>If you are not a user please <a href='{% url 'users:register' %}'>register</a>!</h2>
{% endblock %}

Project3/users/templates/users/register.html
{% extends "users/base.html" %}

{% block body %}
    {% if message %}
        <div>
            {{ message }}
        </div>
    {% endif %}
    
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <input name="username_register" type="text" placeholder="username"/>
        <input name="email_register" type="text" placeholder="email"/>
        <input name="password_register" type="password" placeholder="password"/>
        <input type="submit" value="Register"/>
    </form>
{% endblock %}